# Generated by Django 2.0 on 2018-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='a_type',
            field=models.CharField(choices=[('肉类', '肉类'), ('素食', '素食'), ('主食', '主食'), ('凉菜', '凉菜'), ('汤', '汤'), ('饮品', '饮品'), ('其他', '其他')], max_length=2),
        ),
    ]
