# Generated by Django 2.0 on 2018-01-02 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=20)),
                ('a_picture', models.ImageField(upload_to='a_img/')),
                ('a_foodstuff', models.CharField(max_length=100)),
                ('a_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='data published')),
                ('a_type', models.CharField(choices=[('H', '荤'), ('S', '素'), ('Z', '主食'), ('L', '凉菜'), ('C', '汤'), ('Y', '饮品'), ('Q', '其他')], max_length=2)),
                ('a_words', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_text', models.TextField()),
                ('s_picture', models.ImageField(blank=True, null=True, upload_to='s_img/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Articles')),
            ],
        ),
    ]
