# Generated by Django 2.0 on 2018-01-10 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cook', '0002_auto_20180106_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_foodstuff',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_type',
            field=models.CharField(choices=[('meet', '肉类'), ('vegt', '素食'), ('rice', '主食'), ('cold', '凉菜'), ('soup', '汤'), ('drink', '饮品'), ('else', '其他')], max_length=5),
        ),
    ]
