# Generated by Django 2.0 on 2018-01-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_auto_20180114_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '食谱', 'verbose_name_plural': '食谱'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='userreply',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_foodstuff',
            field=models.TextField(max_length=200, verbose_name='食材'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_name',
            field=models.CharField(max_length=20, verbose_name='菜名'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_picture',
            field=models.ImageField(upload_to='a_img/', verbose_name='主图片'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_shouchang',
            field=models.IntegerField(default=0, verbose_name='收藏量'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_type',
            field=models.CharField(choices=[('meet', '肉类'), ('vegt', '素食'), ('rice', '主食'), ('cold', '凉菜'), ('soup', '汤'), ('drink', '饮品'), ('else', '其他')], max_length=5, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='a_words',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Articles', verbose_name='食谱名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=500, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Articles', verbose_name='食谱'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='s_picture',
            field=models.ImageField(blank=True, null=True, upload_to='s_img/', verbose_name='步骤图片'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='s_text',
            field=models.TextField(max_length=100, verbose_name='步骤'),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Comment', verbose_name='评论id'),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='from_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_who', to=settings.AUTH_USER_MODEL, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='readed',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='reply_text',
            field=models.TextField(max_length=500, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='to_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_who', to=settings.AUTH_USER_MODEL, verbose_name='To'),
        ),
    ]
