# Generated by Django 2.0 on 2018-01-18 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_auto_20180116_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorate',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='收藏的食谱ID'),
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
